options:
  pip-requirements:
    default: requirements.txt
    type: 'string'
    description: |
      The location within your project's directory of any requirements file
      needed to install Python dependencies. An empty string will mean that
      pip will not be run.
  wsgi-file:
    default: ''
    type: 'string'
    description: |
      REQUIRED
      The location of the file which exposes `application` to the WSGI server.

